version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637423318618.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t employeeform1 .
      - docker tag employeeform1:latest 637423318618.dkr.ecr.ap-south-1.amazonaws.com/employeeform:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 637423318618.dkr.ecr.ap-south-1.amazonaws.com/employeeform:latest
